import "oaidl.idl";
import "ocidl.idl";

typedef [	public	]
struct
{
	hyper FunctionOffset;
	hyper TimesCalled;
	hyper ExclusiveTime;
	hyper InclusiveTime;
} FunctionStatistics;

[	object, uuid(2F5ECF23-E98B-4399-AB4F-3083264C481B), nonextensible, pointer_default(unique)	]
interface IProfilerFrontend : IUnknown
{
	HRESULT Initialize([in] BSTR executable, [in] hyper load_address);
	HRESULT UpdateStatistics([in] long count, [in, size_is(count)] FunctionStatistics *statistics);
};

[	uuid(425E45FE-FD05-49C0-A505-93E88651EC36), version(1.0), helpstring("MicroProfiler Frontend 1.0 Type Library")	]
library MicroProfilerFrontendLib
{
	importlib("stdole2.tlb");

	struct FunctionStatistics;

	[ uuid(ABC1A8AB-31D5-475F-B541-987141CD4DB3) ]
	coclass ProfilerFrontend
	{
		[default] interface IProfilerFrontend;
	};
};
