if(NOT ANDROID_ABI OR ANDROID_ABI MATCHES "x86.*")
	if(CMAKE_SIZEOF_VOID_P EQUAL 4)
		if(WIN32)
			set(archid "Win32")
		else()
			set(archid "x86")
		endif()
	else()
		set(archid "x64")
	endif()
elseif(ANDROID_ABI MATCHES "arm.*")
	set(archid "arm")
endif()
