if (DEFINED ENV{VSSDK140Install})
	set(VSSDKROOT $ENV{VSSDK140Install}/VisualStudioIntegration)
elseif (DEFINED ENV{VSSDK120Install})
	set(VSSDKROOT $ENV{VSSDK120Install}/VisualStudioIntegration)
else()
	set(VSSDKROOT $ENV{VSSDK100Install}/VisualStudioIntegration)
endif()
set(VSSDKINCLUDE ${VSSDKROOT}/Common/Inc)
set(VSSDKLIB ${VSSDKROOT}/Common/Lib)
set(VSSDKBIN ${VSSDKROOT}/Tools/Bin)

include_directories(${VSSDKINCLUDE})
include_directories(${CMAKE_CURRENT_LIST_DIR}/../compat/vssdk)
